### ISSUE TITLE
Failed to install having issues with monolog/monolog 2.0.2

### ISSUE THREAD

**Issue by Francis-nova** [Flutterwave/PHP#22]
Trying to install the package in my project 

`our requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for flutterwavedev/flutterwave-v3 ^1.0 -> satisfiable by flutterwavedev/flutterwave-v3[1.0.0].
    - Conclusion: remove monolog/monolog 2.0.2
    - Conclusion: don't install monolog/monolog 2.0.2
    - flutterwavedev/flutterwave-v3 1.0.0 requires monolog/monolog 1.* -> satisfiable by monolog/monolog[1.0.0, 1.0.0-RC1, 1.0.1, 1.0.2, 1.1.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.2.0, 1.2.1, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4, 1.25.5, 1.26.0, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.x-dev].
    - Can only install one of: monolog/monolog[1.0.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.0.0-RC1, 2.0.2].
    - Can only install one of: monolog/monolog[1.0.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.0.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.1.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.10.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.11.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.12.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.13.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.13.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.14.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.15.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.16.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.17.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.18.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.19.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.2.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.2.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.20.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.21.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.24.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.2, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.3, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.4, 2.0.2].
    - Can only install one of: monolog/monolog[1.25.5, 2.0.2].
    - Can only install one of: monolog/monolog[1.26.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.3.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.3.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.4.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.4.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.5.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.6.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.7.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.8.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.9.0, 2.0.2].
    - Can only install one of: monolog/monolog[1.9.1, 2.0.2].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.2].
    - Installation request for monolog/monolog (locked at 2.0.2) -> satisfiable by monolog/monolog[2.0.2].`

Don't really understand why this is happening

**Comment by devsrealm** [comment]
I have a similar issue, any fix for this yet?

**Comment by bajoski34** [comment]
Hi @devsrealm  @Francis-nova this issue has been fixed.

**Comment by JovanDon** [comment]
> Hi @devsrealm @Francis-nova this issue has been resolved.

But am getting the same issue with laravel 6!!!

**Comment by japhyamg** [comment]
> > Hi @devsrealm @Francis-nova this issue has been resolved.
> 
> But am getting the same issue with laravel 6!!!
Have you found a solution to this issue??

**Comment by spectrummfb** [comment]
> Hi @devsrealm @Francis-nova this issue has been resolved.

I'm getting this issue with laravel 8, how do I fix

**Comment by CodeNinjaUG** [comment]
it looks like the monolog version was changed to 1.* which is not working for updated versions of laravel with monolog with version 2

**Comment by JovanDon** [comment]
Check your composer.json file and confirm the exact version of laravel. Is
it 8.0 or you may need to downgrade it!
I once faced this issue and  downgraded to 8.0.  specified my laravel
version like this ""laravel/framework": "^8.0",".

**Comment by salvationarinze** [comment]
@CodeNinjaUG @JovanDon This issue has been resolved. We appreciate your patience

**Comment by CodeNinjaUG** [comment]
Am goin to test it
