### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by chipalo1** [Flutterwave/PHP#30]
"our Composer dependencies require a PHP version ">= 8.0.0"." that is what its saying. I am running php7.4

**Comment by Corvus97** [comment]
Hello @chipalo1 👋🏾,

Thank you for reaching out to the team. We appreciate you sharing your experience with us.

We understand your standpoint. However, to build the best experience for developers, we had to build the library to support at least PHP 8. Kindly upgrade your version of PHP to make use of the library. 

If you run into any issues with your upgrade, please send us a message via [email](mailto:developers@flutterwavego.com).

Join our [community](https://bit.ly/34Vkzcg) to get the latest updates on our APIs, Libraries and developer events.

Cheers!
Cornelius 😊
