### ISSUE TITLE
str.replace is not a function

### ISSUE THREAD

**Issue by paulyeb** [Flutterwave/PHP#33]
I am using a PHP-Laravel API together with Next.js on an application. A click on my Pay Now (checkout) button in the frontend makes an API call to the controller responsible for handling the flutterwave activity. I keep getting the same error of "str.replace not a function" in this manner { **status**:  'error', **message**:  'str.replace is not a function', **data**:  null }. I would appreciate any form of assistance. Attached are screenshot of my codes and the respective error messages.

1. Error message when Pay button is clicked.
![consoled-error-image](https://user-images.githubusercontent.com/86414651/175036066-d653580b-7534-4ca1-ac90-05f9b0874e67.jpg)

2. PHP-Laravel Code
![flutterwave-issue-1](https://user-images.githubusercontent.com/86414651/175036083-5f3934f0-dc68-467a-aece-706c0a180b3c.jpg)

3. PHP-Laravel Code Continuation
![flutterwave-issue-2](https://user-images.githubusercontent.com/86414651/175036085-2635ba8b-0828-477e-a91a-b05073398dc1.jpg)

4. Logged data in Larvel Logger
![flutterwave-logger-image](https://user-images.githubusercontent.com/86414651/175036093-f2265517-8736-411c-a423-588031133dfc.jpg)

**Comment by salvationarinze** [comment]
@paulyeb I could replicate the issue. To proceed, I will recommend you update the package and try again. If, any issue is encountered, please share in detail how to replicate. Thanks
