### ISSUE TITLE
Autoloading using composer

### ISSUE THREAD

**Issue by martonkaufmann** [Flutterwave/PHP#34]
We would like composer to take care of autoloading the classes in the library, but as we found it's not PSR-4 compliant, and we would prefer not to require/include each file one-by-one. 

Is there a recommended approach we should take?
Should we decide to fix the PSR compliancy issue, would you be open to merging it?

**Comment by salvationarinze** [comment]
Hi @martonkaufmann. We apologize for the inconvenience. We have gone ahead to make it PSR-4 compliant. Please update the package. Lastly, please fill free to contribute to the project in order to make it better. Thanks
