### ISSUE TITLE
Flutterwave require(Flutterwave-Rave-PHP-SDK/library/MobileMoney.php): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Deepcodeinnovations** [Flutterwave/PHP#42]
I think this packages has an issue. Am using Laravel 9.5 with PHP 8.1. I have tried a lot of solutions but I seem stuck

![codesnipet](https://user-images.githubusercontent.com/85382663/182522549-28efafd4-2c88-48c0-9ff1-d4e8740704fb.png)

This is my Laravel code
This is the Error i get through my API request

![fluttwaveerror](https://user-images.githubusercontent.com/85382663/182522214-b87856e2-2b78-4ed3-b514-fb3a239b1e9e.png)

Please any one with a solution

**Comment by jsanwo64** [comment]
I think i have a solution

**Comment by jsanwo64** [comment]
Install the package all over. Then show the error you get step by step

**Comment by jsanwo64** [comment]
I was able to install the SDK package successfully (with some errors at first)
