### ISSUE TITLE
Unified Payment Methods Labels and Icon

### ISSUE THREAD

**Issue by zedjasper** [Flutterwave/PHP#43]
Hello,

Can we have the transaction response have a unified payment method label and icon.

Something like
`"payment_method":{
"label": "VISA 363783******36377",
"icon": "https://flutterwave.com/assets/images/payments/visa.png"
}`

I believe this will make it easier and standard for developers to display the icons, especially for all the mobile money platforms

**Comment by Corvus97** [comment]
Hello @zedjasper ,

Thank you very much for sharing this feedback with us.

Please can you send us an email at developers@flutterwavego.com (cc: cornelius@flutterwavego.com) with more details about this feature request?

We are excited to hear more about your request.
