### ISSUE TITLE
Errors in library

### ISSUE THREAD

**Issue by habideen** [Flutterwave/PHP#44]
Hi.

You guys have really done a great job by developing this awesome platform. On the contrary you gave me spitting headache trying to figure why your code does not work. So many bugs in it trying to interface it with laravel application.

In EventHandlerController under onSuccessful($transactionData), 
$transactionData->status returns **successful** not success.

$payment->logger->warning('Stop!!! Please pass the txref parameter!');
not 
$payment->logger->warn('Stop!!! Please pass the txref parameter!'); 
 the method warn was never implemented.

The are tons of these errors but this are the few I can mention for now. 

I look forward to the fix. Thanks, and God bless y'all.

**Comment by bajoski34** [comment]
Hi @habideen thank you for bringing this to our attention. we are looking into it.
