### ISSUE TITLE
Log path

### ISSUE THREAD

**Issue by BUGOVER** [Flutterwave/PHP#51]
How to change log path or disable it

**Comment by bajoski34** [comment]
HI @BUGOVER thanks for choosing flutterwave.

Please kindly create a class that implements the [ConfigInterface](https://github.com/Flutterwave/PHP/blob/master/src/Contract/ConfigInterface.php). An Implementation can be found [here](https://github.com/Flutterwave/PHP/blob/master/src/Helper/Config.php).

**Comment by BUGOVER** [comment]
Please, this is very important and urgent, we have deviated the system and we have problems on the production now.
Thanks again

**Comment by BUGOVER** [comment]
vendor/flutterwavedev/flutterwave-v3/src/Service/Service.php::bootstrap

is called and throws an exception when I try to implement "ConfigInterface"

**Comment by bajoski34** [comment]
hi @BUGOVER please if you are using a service that does not initiate a charge, you need to pass the ConfigInterface as a param. For example :  ```php  use Flutterwave\Service\Banks;
use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__ . "/./");
$dotenv->safeLoad();

$config = CustomConfig::setUp(
    $_SERVER[CustomConfig::SECRET_KEY],
    $_SERVER[CustomConfig::PUBLIC_KEY],
    $_SERVER[CustomConfig::ENCRYPTION_KEY],
    $_SERVER['ENV']
);

$service = new Banks($config);

$bank = $service->getByCountry("NG"); ```
