### ISSUE TITLE
Integration in CodeIgniter 3

### ISSUE THREAD

**Issue by phplime** [Flutterwave/PHP#55]
Hi,
How can I verify a transaction without a .env file 
The problem is when trying to integrate it for multiple users we can't create  .env files for all users.
Need to pass the keys via parameters, how can i do this?

**Comment by bajoski34** [comment]
HI @phplime 

trust you are doing fine. just wanted to know if you still need help with this.

**Comment by bajoski34** [comment]
for custom configuration, you can simply create a class that implements the ConfigInterface and simply pass the secret_key, public_key, encryption key, and env values.

**Comment by phplime** [comment]
Hi @bajoski34 
Thank you for getting back to me. Yes, I got the solution and successfully verified the transaction.

**Comment by bajoski34** [comment]
Great to hear that @phplime. if you have any requests or ideas to better improve the SDK. do let us know. 
Thanks for choosing Flutterwave.
