### ISSUE TITLE
transfers/fee endpoint is returning Application error in PHP

### ISSUE THREAD

**Issue by Philiptebandeke** [Flutterwave/PHP#56]
Hello i am calling endpoint `'https://api.flutterwave.com/v3/transfers/fee'` but getting response `{"error_id":"ERRNO994507623T1678851511558","message":"Application error. Please contact support","code":"app_error"}`  for the last 3 days

my PHP code is;

`    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.flutterwave.com/v3/transfers/fee');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt(
        $ch,
        CURLOPT_POSTFIELDS,
        [
            "type" => "mobilemoney",
            "amount" => 2000,
            "currency" => "UGX",
        ]
    );
    $headers = array();
    $headers[] = 'Authorization: Bearer ' . $fl_secret;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $response = curl_exec($ch);
    if (curl_errno($ch)) {
        mylog('Error:' . curl_error($ch));
        echo '{"status":"error","message":"' . curl_error($ch) . '"}';
        curl_close($ch);
        exit;
    }
    curl_close($ch);`

**Comment by bajoski34** [comment]
Hi @Philiptebandeke Thank you for choosing Flutterwave.

Please note that the endpoint hands get request and as a result it expects query parameters and not `CURLOPT_POSTFIELDS `. please kindly  add the query parameters and try again.

example : https://api.flutterwave.com/v3/transfers/fee?amount=:amount&currency=:currency&type=:momotype

**Comment by Philiptebandeke** [comment]
Thank you it is now fixed
